// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erjbcobzylcdsrerjhup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyamJjb2J6eWxjZHNyZXJqaHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDc3NTgsImV4cCI6MjA2Njg4Mzc1OH0.cfuEPqsV31y4CHb456Ba8xiZjuI_5unXeTJmPV-GBIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});